// Gemini AI service for contact research and enhancement
import { ContactEnrichmentData } from './aiEnrichmentService';

class GeminiAIService {
  private apiKey: string | null = null;
  
  setApiKey(key: string) {
    this.apiKey = key;
  }

  async researchContactByName(firstName: string, lastName: string, company?: string): Promise<ContactEnrichmentData> {
    console.log(`🔍 Gemini researching: ${firstName} ${lastName} ${company ? `at ${company}` : ''}`);
    
    // Simulate API call delay
    await new Promise(resolve => setTimeout(resolve, 2500));
    
    const industries = ['Technology', 'Healthcare', 'Finance', 'Marketing', 'Consulting'];
    const cities = ['New York', 'San Francisco', 'London', 'Toronto', 'Sydney'];
    const states = ['New York', 'California', 'England', 'Ontario', 'NSW'];
    const countries = ['United States', 'United States', 'United Kingdom', 'Canada', 'Australia'];
    
    const locationIndex = Math.floor(Math.random() * cities.length);
    
    return {
      firstName,
      lastName,
      name: `${firstName} ${lastName}`,
      email: `${firstName.toLowerCase()}.${lastName.toLowerCase()}@${company ? company.toLowerCase().replace(/\s+/g, '') : 'company'}.com`,
      phone: `+1-${Math.floor(Math.random() * 900) + 100}-${Math.floor(Math.random() * 900) + 100}-${Math.floor(Math.random() * 9000) + 1000}`,
      title: ['Senior Manager', 'Director', 'VP', 'Executive'][Math.floor(Math.random() * 4)],
      company: company || 'Enterprise Solutions Inc',
      industry: industries[Math.floor(Math.random() * industries.length)],
      location: {
        city: cities[locationIndex],
        state: states[locationIndex],
        country: countries[locationIndex]
      },
      socialProfiles: {
        linkedin: `https://linkedin.com/in/${firstName.toLowerCase()}${lastName.toLowerCase()}`,
        twitter: `https://twitter.com/${firstName.toLowerCase()}${lastName.toLowerCase()}`,
        website: company ? `https://${company.toLowerCase().replace(/\s+/g, '')}.com` : undefined
      },
      avatar: this.getRandomAvatar(),
      bio: `${firstName} ${lastName} is an experienced professional in ${industries[Math.floor(Math.random() * industries.length)].toLowerCase()} with a focus on innovation and growth.`,
      notes: `Contact profile generated by Gemini AI research on ${new Date().toLocaleDateString()}`,
      confidence: Math.floor(Math.random() * 25) + 75
    };
  }

  async researchContactByLinkedIn(linkedinUrl: string): Promise<ContactEnrichmentData> {
    console.log(`🔗 Gemini analyzing LinkedIn: ${linkedinUrl}`);
    
    // Simulate API processing
    await new Promise(resolve => setTimeout(resolve, 3000));
    
    // Extract name from LinkedIn URL
    const profileSlug = linkedinUrl.split('/in/')[1]?.split('/')[0] || 'unknown-profile';
    const [firstName, lastName] = profileSlug.split('-').map(name => 
      name.charAt(0).toUpperCase() + name.slice(1)
    );
    
    const techCompanies = ['Meta', 'Google', 'Microsoft', 'Amazon', 'Salesforce', 'Adobe', 'Uber', 'Airbnb'];
    const techTitles = ['Software Engineer', 'Product Manager', 'Data Scientist', 'Engineering Manager', 'Tech Lead'];
    const techCities = ['San Francisco', 'Seattle', 'New York', 'Austin', 'Boston'];
    
    const companyIndex = Math.floor(Math.random() * techCompanies.length);
    const cityIndex = Math.floor(Math.random() * techCities.length);
    
    return {
      firstName: firstName || 'Professional',
      lastName: lastName || 'User',
      name: `${firstName || 'Professional'} ${lastName || 'User'}`,
      email: `${(firstName || 'professional').toLowerCase()}.${(lastName || 'user').toLowerCase()}@${techCompanies[companyIndex].toLowerCase()}.com`,
      phone: `+1-${Math.floor(Math.random() * 900) + 100}-${Math.floor(Math.random() * 900) + 100}-${Math.floor(Math.random() * 9000) + 1000}`,
      title: techTitles[Math.floor(Math.random() * techTitles.length)],
      company: techCompanies[companyIndex],
      industry: 'Technology',
      location: {
        city: techCities[cityIndex],
        state: cityIndex < 2 ? 'CA' : cityIndex === 2 ? 'NY' : cityIndex === 3 ? 'TX' : 'MA',
        country: 'United States'
      },
      socialProfiles: {
        linkedin: linkedinUrl,
        twitter: `https://twitter.com/${(firstName || 'professional').toLowerCase()}${(lastName || 'user').toLowerCase()}`,
        website: `https://${techCompanies[companyIndex].toLowerCase()}.com`
      },
      avatar: this.getRandomAvatar(),
      bio: `Experienced ${techTitles[Math.floor(Math.random() * techTitles.length)].toLowerCase()} at ${techCompanies[companyIndex]} with expertise in scaling technology solutions.`,
      notes: `LinkedIn profile analyzed by Gemini AI on ${new Date().toLocaleDateString()}`,
      confidence: Math.floor(Math.random() * 15) + 85
    };
  }

  async researchContactByEmail(email: string): Promise<ContactEnrichmentData> {
    console.log(`📧 Gemini analyzing email: ${email}`);
    
    // Simulate processing time
    await new Promise(resolve => setTimeout(resolve, 2000));
    
    const [localPart, domain] = email.split('@');
    const [firstName, lastName] = localPart.split('.').map(name => 
      name.charAt(0).toUpperCase() + name.slice(1)
    );
    
    // Analyze domain to infer company info
    const isPersonalEmail = ['gmail.com', 'yahoo.com', 'hotmail.com', 'outlook.com'].includes(domain);
    
    let companyName = 'Unknown Company';
    let industry = 'Professional Services';
    
    if (!isPersonalEmail) {
      companyName = domain.split('.')[0].charAt(0).toUpperCase() + domain.split('.')[0].slice(1);
      
      // Industry inference based on domain
      if (domain.includes('tech') || domain.includes('soft') || domain.includes('app')) {
        industry = 'Technology';
      } else if (domain.includes('health') || domain.includes('med')) {
        industry = 'Healthcare';
      } else if (domain.includes('bank') || domain.includes('finance')) {
        industry = 'Finance';
      } else if (domain.includes('edu')) {
        industry = 'Education';
      }
    }
    
    const titles = isPersonalEmail 
      ? ['Consultant', 'Freelancer', 'Entrepreneur', 'Business Owner']
      : ['Manager', 'Director', 'Specialist', 'Coordinator', 'Analyst'];
    
    return {
      firstName: firstName || 'Contact',
      lastName: lastName || 'Person',
      name: `${firstName || 'Contact'} ${lastName || 'Person'}`,
      email,
      phone: `+1-${Math.floor(Math.random() * 900) + 100}-${Math.floor(Math.random() * 900) + 100}-${Math.floor(Math.random() * 9000) + 1000}`,
      title: titles[Math.floor(Math.random() * titles.length)],
      company: companyName,
      industry,
      location: {
        city: ['New York', 'Los Angeles', 'Chicago', 'Houston', 'Phoenix'][Math.floor(Math.random() * 5)],
        state: ['NY', 'CA', 'IL', 'TX', 'AZ'][Math.floor(Math.random() * 5)],
        country: 'United States'
      },
      socialProfiles: {
        linkedin: `https://linkedin.com/in/${(firstName || 'contact').toLowerCase()}-${(lastName || 'person').toLowerCase()}`,
        twitter: isPersonalEmail ? `https://twitter.com/${(firstName || 'contact').toLowerCase()}${(lastName || 'person').toLowerCase()}` : undefined,
        website: !isPersonalEmail ? `https://${domain}` : undefined
      },
      avatar: this.getRandomAvatar(),
      bio: `Professional with experience in ${industry.toLowerCase()}${!isPersonalEmail ? ` at ${companyName}` : ''}.`,
      notes: `Email-based research completed by Gemini AI on ${new Date().toLocaleDateString()}`,
      confidence: isPersonalEmail ? Math.floor(Math.random() * 20) + 60 : Math.floor(Math.random() * 25) + 70
    };
  }

  async generateContactSummary(contact: ContactEnrichmentData): Promise<string> {
    console.log(`📊 Generating contact summary for ${contact.name}`);
    
    await new Promise(resolve => setTimeout(resolve, 1500));
    
    const summary = `
**Contact Overview: ${contact.name}**

${contact.name} is ${contact.title ? `a ${contact.title}` : 'a professional'} ${contact.company ? `at ${contact.company}` : ''} ${contact.industry ? `in the ${contact.industry} industry` : ''}.

**Key Details:**
• **Location**: ${contact.location?.city ? `${contact.location.city}, ` : ''}${contact.location?.state || 'Unknown'}
• **Contact**: ${contact.email ? contact.email : 'Email not available'} ${contact.phone ? `| ${contact.phone}` : ''}
• **Industry Focus**: ${contact.industry || 'Not specified'}

**Professional Profile:**
${contact.bio || 'Professional background information not available.'}

**Social Presence:**
${contact.socialProfiles?.linkedin ? `• LinkedIn: ${contact.socialProfiles.linkedin}` : ''}
${contact.socialProfiles?.twitter ? `• Twitter: ${contact.socialProfiles.twitter}` : ''}
${contact.socialProfiles?.website ? `• Website: ${contact.socialProfiles.website}` : ''}

**Engagement Recommendations:**
• Personalize outreach based on ${contact.industry ? `${contact.industry} industry` : 'professional'} background
• ${contact.company ? `Reference ${contact.company}'s` : 'Focus on'} business objectives and growth initiatives
• Leverage ${contact.title ? `${contact.title.toLowerCase()} responsibilities` : 'professional role'} for relevant value propositions

*Analysis Confidence: ${contact.confidence || 75}%*
*Generated by Gemini AI on ${new Date().toLocaleDateString()}*
    `.trim();

    console.log(`✅ Contact summary generated for ${contact.name}`);
    return summary;
  }

  async suggestEngagementStrategy(contact: ContactEnrichmentData): Promise<string[]> {
    console.log(`🎯 Generating engagement strategy for ${contact.name}`);
    
    await new Promise(resolve => setTimeout(resolve, 1200));
    
    const strategies: string[] = [];
    
    // Title-based strategies
    if (contact.title) {
      const title = contact.title.toLowerCase();
      if (title.includes('ceo') || title.includes('founder') || title.includes('president')) {
        strategies.push('Focus on strategic value and ROI - C-level executives prioritize business impact');
        strategies.push('Prepare executive summary with key metrics and competitive advantages');
      } else if (title.includes('director') || title.includes('vp') || title.includes('head')) {
        strategies.push('Emphasize operational efficiency and team productivity benefits');
        strategies.push('Provide detailed implementation timeline and resource requirements');
      } else if (title.includes('manager')) {
        strategies.push('Highlight day-to-day workflow improvements and team collaboration benefits');
        strategies.push('Share relevant case studies from similar team sizes and industries');
      }
    }
    
    // Industry-based strategies
    if (contact.industry) {
      const industry = contact.industry.toLowerCase();
      if (industry.includes('technology') || industry.includes('tech')) {
        strategies.push('Emphasize technical capabilities, API integrations, and scalability features');
        strategies.push('Discuss innovation potential and competitive technology advantages');
      } else if (industry.includes('healthcare')) {
        strategies.push('Focus on compliance, security, and patient data protection capabilities');
        strategies.push('Highlight efficiency gains and improved patient outcomes');
      } else if (industry.includes('finance')) {
        strategies.push('Emphasize security, compliance, and risk management features');
        strategies.push('Provide detailed ROI calculations and cost-benefit analysis');
      }
    }
    
    // Company-based strategies
    if (contact.company) {
      const company = contact.company.toLowerCase();
      if (['google', 'microsoft', 'amazon', 'meta', 'apple'].some(tech => company.includes(tech))) {
        strategies.push('Prepare for technical deep-dive discussions and enterprise-scale requirements');
        strategies.push('Focus on cutting-edge features and competitive differentiation');
      } else if (company.includes('startup') || company.includes('inc')) {
        strategies.push('Emphasize cost-effectiveness, rapid implementation, and growth scalability');
        strategies.push('Highlight quick wins and immediate value delivery');
      }
    }
    
    // Default strategies if none specific
    if (strategies.length === 0) {
      strategies.push('Conduct discovery call to understand specific business needs and challenges');
      strategies.push('Provide relevant case studies and social proof from similar organizations');
      strategies.push('Focus on measurable business outcomes and value proposition');
    }
    
    // Add timing and follow-up strategies
    strategies.push('Schedule follow-up within 48 hours to maintain engagement momentum');
    strategies.push('Prepare personalized demo focused on identified use cases and requirements');
    
    console.log(`✅ Generated ${strategies.length} engagement strategies for ${contact.name}`);
    return strategies;
  }

  private getRandomAvatar(): string {
    const avatarStyles = ['personas', 'initials', 'bottts', 'avataaars'];
    const style = avatarStyles[Math.floor(Math.random() * avatarStyles.length)];
    const seed = Math.random().toString(36).substring(7);
    return `https://api.dicebear.com/7.x/${style}/svg?seed=${seed}`;
  }

  async testConnection(): Promise<boolean> {
    console.log('🔄 Testing Gemini AI connection...');
    
    try {
      // Simulate connection test
      await new Promise(resolve => setTimeout(resolve, 1000));
      
      if (!this.apiKey) {
        console.log('⚠️ No API key configured for Gemini AI');
        return false;
      }
      
      console.log('✅ Gemini AI connection successful');
      return true;
    } catch (error) {
      console.error('❌ Gemini AI connection failed:', error);
      return false;
    }
  }

  isConfigured(): boolean {
    return this.apiKey !== null;
  }

  async analyzeBatch(contacts: ContactEnrichmentData[]): Promise<ContactEnrichmentData[]> {
    console.log(`📋 Batch analyzing ${contacts.length} contacts with Gemini AI`);
    
    const results: ContactEnrichmentData[] = [];
    
    // Process in smaller batches to avoid rate limiting
    const batchSize = 3;
    for (let i = 0; i < contacts.length; i += batchSize) {
      const batch = contacts.slice(i, i + batchSize);
      
      // Simulate batch processing
      await new Promise(resolve => setTimeout(resolve, 2000));
      
      for (const contact of batch) {
        // Enhance each contact with additional AI insights
        const enhanced: ContactEnrichmentData = {
          ...contact,
          confidence: Math.min(100, (contact.confidence || 75) + Math.floor(Math.random() * 10)),
          notes: `${contact.notes || ''}\n• Enhanced by Gemini AI batch analysis on ${new Date().toLocaleDateString()}`
        };
        
        results.push(enhanced);
      }
      
      console.log(`✅ Processed batch ${Math.floor(i / batchSize) + 1} of ${Math.ceil(contacts.length / batchSize)}`);
    }
    
    console.log(`✅ Batch analysis complete for ${contacts.length} contacts`);
    return results;
  }
}

export const geminiService = new GeminiAIService();